version: '3'

services:
  nginx:
    image: nginx
    container_name: nginx-service
    ports:
      - '80:80'
    volumes:
      - ./webserver/conf.d:/etc/nginx/conf.d
      - ./webserver/logs:/var/log/nginx
      - ./app:/var/www/app
    depends_on:
      - php

  php:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: app-service
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: dbuser
      DB_PASSWORD: 222
      DB_NAME: taskmanager
    ports:
      - '9000:9000'
    user: '1000'
    volumes:
      - ./app:/var/www/app
    depends_on:
      - db

  db:
    image: postgres
    container_name: db-container
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=111
      - DB_USER=dbuser
      - DB_PASS='222'
      - DB_NAME=taskmanager

    ports:
      - '5432:5432'
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/postgresql/data

     


